server:
  port: 8088
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  banner:
    location: banner/banner.txt
  application:
    name: biketrack
  profiles:
    active: local

application:
  security:
    jwt:
      secret-key: ZXMKQBBFCLH0ZPAHWN4YGVEGER5NUKD7FGD2321SADA213123DASDGFGFDGBNHJHGE
      access-token-expiration: 30m # 30 minutes
      refresh-token-expiration: 1d  # 1 day
    token:
      account-activation-token-expiration: 15m # 15 minutes
      password-reset-token-expiration: 15m # 15 minutes
  mail:
    enabled: true
    sender-mail: no-reply@biketrack.pl
    sender-name: BikeTrack
  frontend:
    activation-account-url: ${application.frontend.base-url}/active-account
    reset-password-url: ${application.frontend.base-url}/reset-password
  file:
    upload-path: ./uploads
    max-file-size: 10485760 # 10 MB
    max-total-size: 104857600 # 100 MB
    max-files-per-request: 10

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: error