spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/biketrack
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtps
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
  mail:
    enabled: true
  frontend:
    base-url: https://biketrack.tojest.dev