server:
  port: 8088
spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/biketrack
    username: postgres
    password: postgres
  flyway:
    enabled: true
    baseline-on-migrate: true
    table: flyway_schema_history
  servlet:
    multipart:
      max-file-size: 50MB
  mail:
    host: localhost
    port: 1025
    username: mail-dev
    password: mail-dev
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  banner:
    location: banner/banner.txt
  application:
    name: biketrack

application:
  frontend:
    base-url: http://localhost:4200
    activation-url: ${application.frontend.base-url}/activate-account
  security:
    jwt:
      secret-key: ZXMKQBBFCLH0ZPAHWN4YGVEGER5NUKD7FGD2321SADA213123DASDGFGFDGBNHJHGE
      access-token-expiration: 30m # 30 minutes
      refresh-token-expiration: 1d  # 1 day
  mailing:
    is-enabled: true
  file:
    upload:
      photos-output-path: ./uploads