server:
  port: 8088
spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/biketrack
    username: postgres
    password: postgres
  flyway:
    enabled: true
    baseline-on-migrate: true
    table: flyway_schema_history
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  mail:
    host: localhost
    port: 1025
    username: mail-dev
    password: mail-dev
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  banner:
    location: banner/banner.txt
  application:
    name: biketrack

application:
  security:
    jwt:
      secret-key: ZXMKQBBFCLH0ZPAHWN4YGVEGER5NUKD7FGD2321SADA213123DASDGFGFDGBNHJHGE
      access-token-expiration: 30m # 30 minutes
      refresh-token-expiration: 1d  # 1 day
    token:
      account-activation-token-expiration: 15m # 15 minutes
      password-reset-token-expiration: 15m # 15 minutes
  mail:
    enabled: true
    sender-mail: no-reply@biketrack.pl
    sender-name: BikeTrack
  frontend:
    base-url: http://localhost:4200
    activation-account-url: ${application.frontend.base-url}/active-account
    reset-password-url: ${application.frontend.base-url}/reset-password
  file:
    upload-path: ./uploads
    max-file-size: 10485760 # 10 MB
    max-total-size: 104857600 # 100 MB
    max-files-per-request: 10

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: error