CREATE TABLE IF NOT EXISTS _user
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date       TIMESTAMP(6) NOT NULL,
    last_modified_date TIMESTAMP(6),
    email              VARCHAR(255) NOT NULL UNIQUE,
    nickname           VARCHAR(255) NOT NULL UNIQUE,
    password           VARCHAR(255) NOT NULL,
    role               VARCHAR(255) NOT NULL,
    status             VARCHAR(255) NOT NULL,
    uuid               UUID         NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS token
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date       TIMESTAMP(6) NOT NULL,
    last_modified_date TIMESTAMP(6),
    expires_at         TIMESTAMP(6),
    revoked            BOOLEAN      NOT NULL,
    token              VARCHAR(255) NOT NULL UNIQUE,
    token_type         VARCHAR(255) NOT NULL,
    used_at            TIMESTAMP(6),
    user_id            BIGINT       NOT NULL REFERENCES _user
);

CREATE TABLE IF NOT EXISTS bike
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date       TIMESTAMP(6) NOT NULL,
    last_modified_date TIMESTAMP(6),
    created_by         BIGINT       NOT NULL,
    last_modified_by   BIGINT,
    brand              VARCHAR(255),
    description        VARCHAR(255),
    mileage_km         VARCHAR(255),
    model              VARCHAR(255),
    name               VARCHAR(255) NOT NULL,
    photo_uuid         UUID,
    purchase_date      DATE,
    serial_number      VARCHAR(255),
    type               VARCHAR(255) NOT NULL,
    uuid               UUID         NOT NULL UNIQUE,
    user_id            BIGINT       NOT NULL REFERENCES _user
);

CREATE TABLE IF NOT EXISTS repair
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date       TIMESTAMP(6) NOT NULL,
    last_modified_date TIMESTAMP(6),
    created_by         BIGINT       NOT NULL,
    last_modified_by   BIGINT,
    cost               NUMERIC(38, 2),
    currency           VARCHAR(255),
    description        VARCHAR(255),
    repair_date        DATE,
    title              VARCHAR(255) NOT NULL,
    uuid               UUID         NOT NULL UNIQUE,
    bike_id            BIGINT       NOT NULL REFERENCES bike,
    user_id            BIGINT       NOT NULL REFERENCES _user
);


CREATE TABLE IF NOT EXISTS repair_photo
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date       TIMESTAMP(6) NOT NULL,
    last_modified_date TIMESTAMP(6),
    created_by         BIGINT       NOT NULL,
    last_modified_by   BIGINT,
    uuid               UUID         NOT NULL UNIQUE,
    repair_id          BIGINT REFERENCES repair
);